name: FancyPortals
main: com.sniperzciinema.fancyportals.FancyPortals
author: SniperzCiinema
version: 0.0.4
description: Portalllssssss!
website: SniperzCiinema.com
commands:
  FancyPortals:
    description: FancyPortals default command
    usage: /<command>
    aliases: [fp, portal, portals, fportal, fportals, fancyp, fancyportal]
    
permissions:  
  FancyPortals.*:
    default: true
    children:
      FancyPortals.Create: true
      FancyPortals.Use: true
      
  FancyPortals.Use:
    default: true